apiVersion: v1
kind: Secret
metadata:
  name: kerya-secrets
  namespace: kerya-app
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_PASSWORD: "a2VyeWFfcGFzc3dvcmQ="  # kerya_password
  
  # JWT Secret (base64 encoded)
  JWT_SECRET_KEY: "eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV9oZXJlX21ha2VfaXRfbG9uZ19hbmFfcmFuZG9t"
  
  # Encryption Key (base64 encoded)
  ENCRYPTION_KEY: "eW91cl8zMl9jaGFyYWN0ZXJfZW5jcnlwdGlvbl9rZXlfaGVyZQ=="
  
  # AWS S3 Credentials (base64 encoded)
  AWS_ACCESS_KEY_ID: "eW91cl9hd3NfYWNjZXNzX2tleV9pZA=="
  AWS_SECRET_ACCESS_KEY: "eW91cl9hd3Nfc2VjcmV0X2FjY2Vzc19rZXk="
  
  # SendGrid API Key (base64 encoded)
  SENDGRID_API_KEY: "eW91cl9zZW5kZ3JpZF9hcGlfa2V5"
  
  # Twilio Credentials (base64 encoded)
  TWILIO_ACCOUNT_SID: "eW91cl90d2lsaW9fYWNjb3VudF9zaWQ="
  TWILIO_AUTH_TOKEN: "eW91cl90d2lsaW9fYXV0aF90b2tlbg=="
  
  # Google Maps API Key (base64 encoded)
  GOOGLE_MAPS_API_KEY: "eW91cl9nb29nbGVfbWFwc19hcGlfa2V5"
  
  # Stripe Keys (base64 encoded)
  STRIPE_SECRET_KEY: "eW91cl9zdHJpcGVfc2VjcmV0X2tleQ=="
  STRIPE_PUBLISHABLE_KEY: "eW91cl9zdHJpcGVfcHVibGlzaGFibGVfa2V5"
  STRIPE_WEBHOOK_SECRET: "eW91cl9zdHJpcGVfd2ViaG9va19zZWNyZXQ="
  
  # OAuth 2.0 Credentials (base64 encoded)
  GOOGLE_CLIENT_ID: "eW91cl9nb29nbGVfY2xpZW50X2lk"
  GOOGLE_CLIENT_SECRET: "eW91cl9nb29nbGVfY2xpZW50X3NlY3JldA=="
  
  # Elasticsearch Password (base64 encoded)
  ELASTICSEARCH_PASSWORD: "Y2hhbmdlbWU="  # changeme
  
  # Redis Password (base64 encoded) - empty for default
  REDIS_PASSWORD: ""
  
  # RabbitMQ Credentials (base64 encoded)
  RABBITMQ_USER: "Z3Vlc3Q="  # guest
  RABBITMQ_PASSWORD: "Z3Vlc3Q="  # guest 